server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
  mail:
    host: smtp.qq.com
    # 你的QQ邮箱，这里为发件人，填自己的即可
    username: 3755579845@qq.com
    # 你的QQ邮箱授权码
    password: znkmvoszapfmchhj
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\img1\


alipay:
  # appid
  app_id: 9021000135614391
  # 应用私钥
  rsa_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDOl4lCabueygC+sxS2PYaWm8c+Tmc1wHqZLwRThgzqHA1W9ORBakdqNZBFFw0NMqnK4DeFSwaPnT+uEgJR7til5CPex6riOAc2rI2c33m2fsS/8OeRjLxgxRYbMjf486fPZecvqmRVLLynxJcuCq+Lg56wBc83bGw+9YornLIgMOqdHNHU7ntDIj+88YRJUymOYJAnJXbba6GC71SJqLrrOaMOO10luoKBE7GYp62oYrcdrEhMLaFQuJFUC17xWFgefsKp94keZJmAhSV8Me2f2ceW4SsE2zmFt3XoXYUhFi43FqADk3jEW5sqXqi0P0zEbFHdZ3S+IHOtXZ8BWPXPAgMBAAECggEAYoWV6dwuo51GGauhlv9kbfLAZBBT3Ch8zwzDDWoCQqs6GVwUdrXOdPIyaSCDEuY0XxHqqGCNMnQVaFgiTxyOqR5RlO63qcZ6ejJ0Hnncu5FdFwQ2Cw2I0MVss2+RjeH1B01boTmrO4toNMHmLwjdirUsOlmq5o2IWcYTLJU/xWVy/f3bpuSSvZacEY+u5Sp7Sh57xKETObsQ9Llb8P+ODstjrgk2zJqqtZAvgmjtTbkO/yUdPsAqfFgqojgdFdZz3rQgVhGECmYOnOoOSjAMPtbMNvhOd9DbllQ4gaxpWqC4zXTsXWzUY5zdbxh6oxblI3Y54jNiTo/WznOOSoox8QKBgQDxzf0+ealydwg0C/+Izfbn70l00JxBIiM20Tg/GeDfuQ85gVu74P8TY6BxTcXuJCZF8ZOH4X+yocN3V3RLFr24qATyGPxbJxzTWeUj1jqbXpQ2EB+mDVGnagMKMeTIozDeLhEMH5En7L7oAbDKw+yInm9Ox9HjXvMpUqKX7iaMkwKBgQDauFh03Rgq1mlJqZux8/PiLPFpt2D+VHdcl1JDmRE0q8oZZfnAk2cGEohTa/QMjikbBKXtfAQsRnOxXmJM/pDpLAD09x+g3or7DnTMKM47YOm9QGhj261i71xLr+DqslVm/B12xvRC+sHlAmU3JEpgdiqkGToesuuFtCPZbykzVQKBgAMgBWjcS6tWDH4XtZrABrPirNFcrNhOp6Paul5eaECb9K1qlZPtCX7np7gvKCK2xuPahmyYJn1Zh9wv/inGRndvfHjgh8ppy/6TR9nZt/IwG7xDIxWTUH3Yaeek028gZM5KTCAa/FZGwgTfmLhWJeVyHsAm5viITp43GjDafBcPAoGAVyiG92rzqn5uzo/sH2nbkhHe0gXlfPQj7J3QhmeE17xteNmOQRN8Ros0ECpAwpAUCVQ82vpEn3AjwlaeTZhUHtcOOpAP5odIUutb18+a/0aLXoNAFisAWSCRYwffVSdjqPpms2JtDBPpGF1wAB1SFkaAj4wOARXDjTBP6OHHRVECgYEAkqPSjUKT7k4yKcW19GZs0VHB26FT4OhAtUaxPvByDEWgWbYPd1JCdLKRSDgO8Ma2BEiabcp+m+wEsJFhsw7w0LOvWWL40fhWkfWdakr1Hq1LxI9lsfuIzNOOg2DZRaomCSEIwokQ8f+lPdKl7b4IoUc3b2cJbVO9Y/fCjlccm/A=
  # 服务器异步通知页面路径 需http://或者https://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  notify_url: http://aze35d.natappfree.cc/order/notify
  # 页面跳转同步通知页面路径 需http://或者https://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  return_url: http://aze35d.natappfree.cc/order/return
  # 请求网关地址
  # 正式为："https://openapi.alipay.com/gateway.do"
  url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  # 编码
  charset: UTF-8
  # 返回格式
  format: json
  # 支付宝公钥
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjaYUhdhXK7/CpU9qpw3DPbc/yCei0mLPT3oy1RIkjTQX5uAPesO7L2XMa4emPvJ7ljDUUsQ3c7VULDsGANmuf8dcT02lwEAhz7kUS/RogQmYWPUfr57tQhw7GpNnZcEpLFt/jk1rYHXtJkq5aDeYLDbuCCvEzrJyJ97xXCvA21dLE54y+ksh3IwwECMdSyirn1kXvcA+AVDx/5jboY3s7tpMmb/EaXahxHD2JKk9QUg7PKSvmpfSFIBsHUbdSJxO8rnJOeE6gCmp0mwIbgmR/JqM+ZmRhwbVUpBB0dM+jmNDkMxWZK+hcdCZGO4o3fIa5TylFgF165UxdhNbd9pnTwIDAQAB
  # RSA2
  sign_type: RSA2